apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-cmp
  namespace: argocd
  annotations:
    argocd.argoproj.io/refresh: hard
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: '*'
    plugin:
      name: argo-helm-parameters
      env:
        - name: HELM_RELEASE_NAME
          value: a-sample
        - name: HELM_CHART
          value: nginx

