name: "kgc"
version: "1.25.1"
usage: "helm kgc configmapName"
description: "get a configmap key named values.yaml by configmap name"
ignoreFlags: false
command: "source  $HELM_PLUGIN_DIR/bin/kgc.sh"
useTunnel: false
hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/install.sh"
  update: "cd $HELM_PLUGIN_DIR; scripts/install.sh"
